console.log("Hello world!")
console.log(document.body.childNodes)
console.log(document.body.childNodes[1].childNodes)
let cont = document.body.childNodes[1]
console.log(cont.firstChild)
console.log(cont.lastChild)
console.log(cont.firstElementChild)
console.log(cont.lastElementChild)
console.log(cont.lastElementChild.style.color = "yellow")
console.log(cont.lastElementChild.style.backgroundColor = "black")
console.log(cont.lastElementChild.parentElement)
console.log(document.body.firstElementChild)
console.log(document.body.firstElementChild.childNodes)
console.log(document.body.firstElementChild.children)
console.log(document.body.firstElementChild.children[0])
console.log(document.body.firstElementChild.children[1])
console.log(document.body.firstElementChild.children[2])
console.log(document.body.firstElementChild.children[3])
console.log(document.body.firstElementChild.children[4])
console.log(document.body.firstElementChild.children[0].nextSibling)
console.log(document.body.firstElementChild.children[0].nextElementSibling)
console.log(document.body.firstElementChild.children[4].previousSibling)
console.log(document.body.firstElementChild.children[4].previousElementSibling)
console.log(document.body.firstElementChild.children[4].parentElement)
console.log(document.body.children)


